---
type: prd
title: "{{TITLE}}"
slug: "{{SLUG}}"
status: draft
phase: 01
created: {{DATE}}
updated: {{DATE}}
generated_by: sdlc-prd
owner: "{{OWNER}}"
tags: [planning, prd]
stakeholders: []
target_date: ""
---

# {{TITLE}}

> _(Initiative PRD — describes WHAT and FOR WHOM, leaving HOW to specs.)_

## Context

Current situation and what motivates this initiative. 2–4 paragraphs.

## Problem

The specific problem this initiative solves. Be concrete: for whom, how often, with what impact.

## Hypotheses

Assumptions we need to validate.

- **H1:** <hypothesis> — _validated by_ <metric/experiment>.
- **H2:** <hypothesis> — _validated by_ <metric/experiment>.

## Scope

### In scope

- <item>
- <item>

### Out of scope

- <item explicitly not included>
- <item>

## KPIs

| KPI | Baseline | Target | Timeline |
|---|---|---|---|
| <ex: conversion rate> | <current value> | <desired value> | <date> |

## Risks

| Risk | Probability | Impact | Mitigation |
|---|---|---|---|
| <risk 1> | low/medium/high | low/medium/high | <action> |

## Schedule

- **Kickoff:** {{DATE}}
- **Milestone M1:** <date> — <scope>
- **Milestone M2:** <date> — <scope>
- **GA:** <date>

## Stakeholders

- **Sponsor:** <name, role>
- **Product Owner:** {{OWNER}}
- **Tech Lead:** <name>
- **Design Lead:** <name>
- **Consulted stakeholders:** <list>

## Linked epics

_(regenerated by the librarian — wikilinks to epics for this initiative)_

- [[<epic-slug>]] — <short title>

## References

- [[product]] — product vision
- [[_INDEX]] — global index
