# {{PROJECT_NAME}} — SDLC Vault Doctrine

> **This file is sovereign.** No skill edits it automatically. Every AI working in this vault MUST read it before any write operation.

- **Created:** {{DATE}}
- **Stack:** {{STACK}}
- **Owner:** {{OWNER}}
- **Repository:** {{REPO_URL}}

---

## 1. Non-negotiable rules for the LLM

1. **Read this file** before any write to the vault. It defines the boundaries.
2. **Never edit this `CLAUDE.md`** without explicit user permission.
3. **Never manually edit `_INDEX.md`** — it is regenerated by `/sdlc-kit:sync`.
4. Every feature starts with `/sdlc-kit:spec <feature>` — SDD trio (requirements + design + tasks) is mandatory.
5. Every document created must have **complete frontmatter** per the schema below.
6. Every document must have **at least 1 wikilink** to another note in the vault (connected graph).
7. After any write, the calling skill must invoke `/sdlc-kit:sync`.
8. **No files** outside the 8 canonical folders (`00-07`).
9. **File names:** kebab-case, no accents, no spaces. Example: `login-with-google.md`.
10. **Language:** English in titles, body, and user prompts. Code remains in the natural language of the stack.

---

## 2. Conceptual hierarchy

```
PRD                      (01-planning/prd/)         — product initiative
  └─ Epic                (01-planning/epics/)       — large deliverable; stories as bullets in ## Stories
       └─ Spec           (04-specs/<feature>/)      — SDD trio for feature
            ├─ requirements.md   (testable EARS)
            ├─ design.md         (technical design)
            └─ tasks.md          (executable task list)
                 └─ Task          — references REQ-NNN and, if API, contract in 02-architecture/api/
```

In parallel:
- **Milestone** (`01-planning/milestones/`) groups epics by delivery date.
- **Sprint** (recorded in SQLite, no folder) groups tasks by time cycle.
- **ADR** (`02-architecture/adr/`) captures irreversible or expensive-to-revert architectural decisions.

---

## 3. Story vs. requirement boundary (critical — do not confuse)

| Artifact | Location | Format | Author | Answers |
|---|---|---|---|---|
| **Story** | Bullet in `01-planning/epics/<slug>.md` (section `## Stories`) | *"As X, I want Y, so that Z"* | Product | **WHAT + FOR WHOM** |
| **Requirement** | `04-specs/<feature>/requirements.md` (REQ-NNN) | EARS: `WHEN <trigger> THE SYSTEM SHALL <behavior>` | Tech | **HOW TO TEST** |

One story may become multiple specs; one spec contains multiple requirements; one requirement becomes one or more tasks. **Stories are not skills or separate files** — they live as bullets within the epic.

---

## 4. Frontmatter schema

**Mandatory fields in every document:**

```yaml
---
type: <see table below>
title: "Readable title"
slug: "slug-kebab-case"
status: draft | in-review | accepted | active | done | archived
phase: "00" | "01" | "02" | "03" | "04" | "05" | "06" | "07"
created: YYYY-MM-DD
updated: YYYY-MM-DD
generated_by: sdlc-<skill-name>
owner: "{{OWNER}}"
tags: [<tag1>, <tag2>]
---
```

**`type` values by folder:**

| Folder | Valid `type` |
|---|---|
| 00-steering/ | `steering-product`, `steering-tech`, `steering-standards` |
| 01-planning/prd/ | `prd` |
| 01-planning/epics/ | `epic` |
| 01-planning/milestones/ | `milestone` |
| 02-architecture/adr/ | `adr` |
| 02-architecture/c4/ | `c4-context`, `c4-container`, `c4-component` |
| 02-architecture/trd/ | `trd` |
| 02-architecture/api/ | `api-rest`, `api-grpc`, `api-async`, `api-webhook` |
| 03-domain/ | `context-map`, `ubiquitous-language`, `aggregate`, `domain-event`, `contract` |
| 04-specs/<feature>/ | `spec-requirements`, `spec-design`, `spec-tasks` |
| 05-development/ | `worktree`, `branch` |
| 06-design-system/ | `ds-token`, `ds-component`, `ds-pattern` |
| 07-retrospectives/ | `retro`, `review`, `incident`, `incident-lessons` |

**Additional relevant fields (by type):**

- `adr`: `decision_date`, `supersedes`, `superseded_by`
- `epic`: `prd`, `milestone`, `estimate`
- `spec-*`: `feature`, `epic`
- `incident`: `severity` (SEV1-4), `detected_at`, `mitigated_at`, `resolved_at`, `mttr_minutes`
- `api-*`: `auth`, `version`

---

## 5. Phase map

| Folder | Responsibility |
|---|---|
| `00-steering/` | Product vision, technical principles, team standards (Kiro-style) |
| `01-planning/` | PRDs, epics (with embedded stories), milestones |
| `02-architecture/` | ADRs, C4 diagrams, TRDs (cross-feature), API contracts |
| `03-domain/` | DDD: context-map, ubiquitous language, aggregates, events, ACL contracts |
| `04-specs/` | SDD trio per feature (requirements + design + tasks) |
| `05-development/` | Worktree logs and branch↔task↔PR correlation |
| `06-design-system/` | Design System tokens, components, and patterns |
| `07-retrospectives/` | Sprint retros, PR code reviews, incidents + lessons learned |

Ops/deployment **outside** the vault (runbooks in Notion, alerts in Grafana). The vault only records *closed incidents*.

---

## 6. Skill inventory

| Skill | Use |
|---|---|
| `/sdlc-kit:init` | Scaffolds the vault (one time only) |
| `/sdlc-kit:sync` | Reindexes + regenerates `_INDEX.md` |
| `/sdlc-kit:status` | Vault health report |
| `/sdlc-kit:dash` | Opens `dashboard.html` in browser |
| `/sdlc-kit:steer {product\|tech\|standards}` | Edits steering docs |
| `/sdlc-kit:prd {new\|list\|update\|approve}` | PRDs |
| `/sdlc-kit:epic {new\|list\|close}` | Epics (with stories as bullets) |
| `/sdlc-kit:milestone {new\|status\|close}` | Milestones |
| `/sdlc-kit:adr {new\|supersede\|list}` | ADRs |
| `/sdlc-kit:c4 {context\|container\|component}` | C4 diagrams |
| `/sdlc-kit:trd {new\|list}` | Technical Requirements Docs |
| `/sdlc-kit:domain {event-storm\|context-map\|aggregate\|event\|language}` | DDD |
| `/sdlc-kit:spec {new\|requirements\|design\|tasks\|approve}` | SDD trio |
| `/sdlc-kit:spec api {rest\|grpc\|async\|webhook} <feature>` | API contract |
| `/sdlc-kit:task {add\|complete\|list}` | Tasks in a spec |
| `/sdlc-kit:worktree {list\|scaffold\|transition}` | Git worktrees and branches |
| `/sdlc-kit:design-system {list\|scaffold\|transition}` | Design System (tokens/components/patterns) |
| `/sdlc-kit:retro {list\|scaffold\|transition}` | Sprint retrospectives |
| `/sdlc-kit:incident {list\|scaffold\|transition}` | Incidents & post-mortems |
| `/sdlc-kit:review {list\|scaffold\|transition\|decide}` | PR code reviews |
| `/sdlc-kit:review {pr\|post-impl\|list}` | Code reviews |
| `/sdlc-kit:incident {new\|resolve\|lessons}` | Incidents (lessons auto via hook) |
| `/sdlc-kit:trace {<term>\|spec\|adr}` | Cross-vault tracing |
| `/sdlc-kit:impact {<file>\|spec\|adr}` | Impact analysis |
| `/sdlc-kit:doc {new\|glossary\|readme}` | Loose notes |

---

## 7. Writing conventions

- **Wikilinks preferred** over relative paths: `[[<slug>]]` instead of `../04-specs/x.md`.
- **`status: draft`** in every newly-created artifact. Only the user promotes to `accepted`/`active`/etc.
- **Dates** in ISO 8601 (`YYYY-MM-DD`).
- **ADR numbers** with 4 digits: `ADR-0001`, `ADR-0012`.
- **Mermaid preferred** for diagrams. C4 uses `C4Context`/`C4Container`/`C4Component`.
- **EARS mandatory** in `spec-requirements`. One of 5 formats: ubiquitous / event / state / condition / event+precondition.
- **Test coverage ≥ 90%** in critical packages (per team standard in `00-steering/standards.md`).

---

## 8. Technology stack

{{STACK_DETAILS}}

---

## 9. Active bounded contexts

Consult [[context-map]] in `03-domain/context-map.md`. If empty, run `/sdlc-kit:domain context-map` to model.

---

## 10. References

- [[_INDEX]] — live vault index (regenerated by sync)
- `dashboard.html` — self-contained HTML dashboard (open with `/sdlc-kit:dash`)
- ADR-0001 (plugin) — canonical structure of 8 folders
- ADR-0002 (plugin) — skill inventory
