---
type: index
title: "Index — {{PROJECT_NAME}}"
status: active
generated_by: sdlc-sync
updated: {{SYNC_TS}}
---

# Index — {{PROJECT_NAME}}

> Auto-generated by `/sdlc-kit:sync`. **Do not edit manually.**
> Last sync: **{{SYNC_TS}}**

---

## Overview

| Metric | Value |
|---|---|
| Active sprint | — |
| Active milestone | — |
| Active epics | 0 |
| In-progress specs | 0 |
| Open tasks | 0 |
| Completed tasks | 0 |
| Open incidents | 0 |
| Recorded ADRs | 0 |

---

## Direction (00-steering)

- [ ] `product.md` — Product vision — _pending_
- [ ] `tech.md` — Technical principles — _pending_
- [ ] `standards.md` — Team standards — _pending_

## Planning (01-planning)

### PRDs
_No PRDs recorded. Run `/sdlc-kit:prd new "<initiative>"._

### Epics
_No epics recorded._

### Milestones
_No milestones recorded._

## Architecture (02-architecture)

### ADRs
_No ADRs recorded. Run `/sdlc-kit:adr new "<title>"` for the first decision._

### C4
- [ ] `context.md` — Level 1 (Context) — _pending_
- [ ] `container.md` — Level 2 (Containers) — _pending_
- [ ] `component.md` — Level 3 (Components) — _pending_

### TRDs
_No TRDs recorded._

### APIs
_No API contracts recorded. Run `/sdlc-kit:spec api {rest\|grpc\|async\|webhook} <feature>`._

## Domain (03-domain)

- [ ] `context-map.md` — Bounded contexts map — _pending_
- [ ] `ubiquitous-language.md` — Glossary — _pending_

_No aggregates, events, or contracts recorded._

## Specs (04-specs)

_No specs created. Run `/sdlc-kit:spec new <feature>` for the SDD trio (requirements + design + tasks)._

## Development (05-development)

### Worktrees
_No active worktrees._

### Tracked branches
_No branches recorded._

## Design System (06-design-system)

_Empty. Run `/sdlc-kit:design-system {token\|component\|pattern} <name>` when you start documenting the DS._

## Retrospectives (07-retrospectives)

### Retros
_No retros recorded. Run `/sdlc-kit:retro` to capture the first retrospective._

### Code Reviews
_No reviews recorded._

### Incidents
_No incidents recorded._

---

## Detected anomalies

_No anomalies._

---

## Useful shortcuts

- [[CLAUDE]] — vault doctrine (required reading)
- `dashboard.html` — self-contained dashboard (run `/sdlc-kit:dash` to open)
- `/sdlc-kit:status` — health report via CLI
